version: '3'

services:
    web:
        deploy:
            restart_policy:
                condition: any
        build:
            dockerfile: Dockerfile
            context: pharmiq-web/
        ports:
            - 80:80
        image: lifestores/pharmiq-web:dev
#Volumes
volumes:
    pharmiq_data:
  
  
        